CREATE TABLE PRICE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE_AMOUNT DECIMAL,
    CURRENCY VARCHAR(3)
);